# --- Hardware Buses ---
CONFIG_I2C=y
CONFIG_SPI=y

# --- Emulator Framework ---
CONFIG_EMUL=y

# --- Math & Floating Point Support ---
CONFIG_FPU=y

# --- Memory Allocation ---
# Give the stack and heap plenty of breathing room 
# for the 64-bit math and large SPI DMA arrays.
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=4096